version: "3"

networks:
  todo:
    driver: bridge

services:
  spring-boot-app:
    build:
      context: ./Server
    networks:
      - todo

  react-app:
    build:
      context: ./Client
    networks:
      - todo