spring:
  datasource:
    url: jdbc:h2:file:./h2db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
    console.path: /h2-console
hibernate:
  hbm2ddl:
    auto: create
server:
  port: 8080

